baseurl: https://alexnorell.github.io/ethdenver-how-to-build-a-scalable-dapp/
theme: hugo-webslides
languageCode: en-us
title: How to deploy and scale a Dapp
params:
  author: Alex Norell
  homepage: https://alexnorell.com
  webslides:
    banner: false
    slideshow: true
    vertical: false
    autoslide: false
    changeOnClick: false
    disableLoop: false
    minWheelDelta: 40
    disableNavigateOnScroll: false
    scrollWait: 450
    slideOffset: 50
    hideIndex: false
markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
