baseurl: /
theme: hugo-webslides
languageCode: en-us
title: How to deploy and scale a Dapp
params:
  author: Alex Norell
  homepage: alexnorell.com
  webslides:
    banner: false
    slideshow: true
    vertical: false
    autoslide: false
    changeOnClick: false
    disableLoop: false
    minWheelDelta: 40
    disableNavigateOnScroll: false
    scrollWait: 450
    slideOffset: 50
    hideIndex: false
blackfriday:
  extensionsmask:
    - autoHeaderIds
